### ISSUE TITLE
NHS UK icon class overrides icon size props

### ISSUE THREAD

**Issue by luqmanyasin** [rowellx68/nhs-components#155]
When implementing the `CloseIcon` I've come across an issue where the size `width` and `height` properties are overridden by the `nhsuk-icon` class which specifies width and height of `34px` in the css.

https://github.com/rowellx68/nhs-components/blob/main/packages/nhsuk-frontend-react/src/icons/close/Close.tsx

**Comment by rowellx68** [comment]
Maybe we should remove the custom `width` and `height` properties since the CSS overrides it anyway.

**Comment by luqmanyasin** [comment]
Agreed, that makes more sense
