### ISSUE TITLE
Fieldset.Legend does not support `isPageHeading` prop

### ISSUE THREAD

**Issue by graham-a3** [rowellx68/nhs-components#90]
isPageHeading prop should add the class `nhsuk-fieldset__legend--xl` when true

**Comment by rowellx68** [comment]
This should be achievable by setting the `Fieldset.Legend` variant to `page-heading`.

**Comment by graham-a3** [comment]
That worked great, thank you. I'll leave this open so we can get it documented

**Comment by rowellx68** [comment]
This should be fixed in [v3.5.1](https://github.com/rowellx68/nhs-components/releases/tag/nhsuk-frontend-react%403.5.1).
