### ISSUE TITLE
DateInput onChange type oddities

### ISSUE THREAD

**Issue by graham-a3** [rowellx68/nhs-components#91]
The type for the DateInput's onChange handler seems to resolve to `React.FormEvent<HTMLDivElement> | DateInputChangeEvent`.

![image](https://github.com/user-attachments/assets/7fd7b8a0-7c6f-4308-b459-fe3774dcf211)

I would expect it to be `DateInputChangeEvent`.

Current work around is to explicitly set the type:

![image](https://github.com/user-attachments/assets/54a04fce-a9be-43ff-a1f8-15f34e081eed)

**Comment by rowellx68** [comment]
This should be fixed in [v3.5.1](https://github.com/rowellx68/nhs-components/releases/tag/nhsuk-frontend-react%403.5.1).
