### ISSUE TITLE
DateInput cannot be disabled / there is no disabled prop

### ISSUE THREAD

**Issue by graham-a3** [rowellx68/nhs-components#92]
![image](https://github.com/user-attachments/assets/78af38ef-d314-4a21-9251-659a0ea9970b)

I would expect to be able to disable the DateInput

**Comment by rowellx68** [comment]
This should be fixed in [v3.5.1](https://github.com/rowellx68/nhs-components/releases/tag/nhsuk-frontend-react%403.5.1).
