### ISSUE TITLE
Tag component does not have a style prop

### ISSUE THREAD

**Issue by graham-a3** [rowellx68/nhs-components#95]
![image](https://github.com/user-attachments/assets/d7264fbb-fb7e-4806-9086-d273172188d1)

I would expect to be able to apply styles via the style prop, like I can with the Button component

**Comment by rowellx68** [comment]
This should be fixed in [v3.5.1](https://github.com/rowellx68/nhs-components/releases/tag/nhsuk-frontend-react%403.5.1).
